services:
  app:
    build: .
    image: ghcr.io/birabittoh/artbound-python:main
    container_name: artbound-python
    ports:
      - 127.0.0.1:1111:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - cache:/app/artbound_python/static/res/cache/
      - ${PWD}/.env:/app/.env
      - ${PWD}/credentials.json:/app/credentials.json
      - ${PWD}/token.json:/app/token.json
volumes:
  cache:
